services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application 
             --access-logfile /app/var/logs/gunicorn_access.log
             --error-logfile /app/var/logs/gunicorn_error.log
             --bind 0.0.0.0:8000"
    volumes:
      - ${DJANGO_DB_VOLUME:-hyperadmin_db_data}:/app/var/db
      - ${DJANGO_STATIC_VOLUME:-hyperadmin_static_data}:/app/var/static
      - ${DJANGO_MEDIA_VOLUME:-hyperadmin_media_data}:/app/var/media
      - ${DJANGO_LOGS_VOLUME:-hyperadmin_logs_data}:/app/var/logs
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

  worker:
    build: .
    command: >
      sh -c "python manage.py qcluster"
    volumes:
      - ${DJANGO_DB_VOLUME:-hyperadmin_db_data}:/app/var/db
      - ${DJANGO_STATIC_VOLUME:-hyperadmin_static_data}:/app/var/static
      - ${DJANGO_MEDIA_VOLUME:-hyperadmin_media_data}:/app/var/media
      - ${DJANGO_LOGS_VOLUME:-hyperadmin_logs_data}:/app/var/logs
    depends_on:
          web:
            condition: service_healthy
    networks:
      - default
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    volumes:
    - ./nginx:/etc/nginx/conf.d:ro
      - ${DJANGO_STATIC_VOLUME:-hyperadmin_static_data}:/app/var/static
      - ${DJANGO_MEDIA_VOLUME:-hyperadmin_media_data}:/app/var/media
      - ${DJANGO_LOGS_VOLUME:-hyperadmin_logs_data}:/app/var/logs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.hyperadmin.rule=PathPrefix(`/hyperadmin`)"
      - "traefik.http.routers.hyperadmin.entrypoints=websecure"
      - "traefik.http.routers.hyperadmin.tls=true"
      - "traefik.http.services.hyperadmin.loadbalancer.server.port=80"
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
volumes:
  hyperadmin_db_data:
  hyperadmin_static_data:
  hyperadmin_media_data:
  hyperadmin_logs_data: