services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --access-logfile /app/var/logs/gunicorn_access.log --error-logfile /app/var/logs/gunicorn_error.log core.wsgi:application"
    volumes:
      - ${DJANGO_DB_VOLUME:-hyperdossier_db_data}:/app/var/db
      - ${DJANGO_STATIC_VOLUME:-hyperdossier_static_data}:/app/var/static
      - ${DJANGO_MEDIA_VOLUME:-hyperdossier_media_data}:/app/var/media
      - ${DJANGO_LOGS_VOLUME:-hyperdossier_logs_data}:/app/var/logs
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hyperdossier/health/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

  nginx:
    build:
      context: ./nginx
    depends_on:
      - web
    volumes:
      - ${DJANGO_STATIC_VOLUME:-hyperdossier_static_data}:/app/var/static
      - ${DJANGO_MEDIA_VOLUME:-hyperdossier_media_data}:/app/var/media
      - ${DJANGO_LOGS_VOLUME:-hyperdossier_logs_data}:/app/var/logs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.hyperdossier.rule=PathPrefix(`/hyperdossier`)"
      - "traefik.http.routers.hyperdossier.entrypoints=websecure"
      - "traefik.http.routers.hyperdossier.tls=true"

      - "traefik.http.routers.hyperdossier.service=hyperdossier"
      - "traefik.http.services.hyperdossier.loadbalancer.server.port=80"
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
volumes:
  hyperdossier_db_data:
  hyperdossier_static_data:
  hyperdossier_media_data:
  hyperdossier_logs_data: